field_separator: "\t"

dataset: Amazon_Movies_and_TV
file_name: Amazon_Movies_and_TV
data_path: /home/tasi2425107/MyProjectExport/Dataset/movie/Amazon_Movies_and_TV_GPT

model: CKE

embedding_size: 50
kg_embedding_size: 50
reg_weights: [1e-5, 1e-5]

learning_rate: 0.001
train_batch_size: 40960
epochs: 20
topk: [10, 20]

load_col:
  inter: [user_id, item_id, rating]
  kg: [head_id, relation_id, tail_id]
  link: [item_id, entity_id]

HEAD_ENTITY_ID_FIELD: head_id
TAIL_ENTITY_ID_FIELD: tail_id
RELATION_ID_FIELD: relation_id

eval_args:
  split: {'RS': [0.6, 0.2, 0.2]}
  mode: full
  order: RO
metrics: [Recall, NDCG, MRR, Hit]
