# Path ops (jika custom data)
data_path: /home/tasi2425107/MyProjectExport/Dataset/movie/Amazon_Movies_and_TV_GPT

# cke_config.yaml

model: CKE

# knowledge-aware setting
load_col:
  inter: [user_id, item_id, rating]
  kg: [head_id, relation_id, tail_id]
  link: [item_id, entity_id]

# General settings
embedding_size: 50
learning_rate: 0.001
train_batch_size: 40960
eval_batch_size: 40960

# Training settings
epochs: 300
early_stop: True
stopping_step: 10

# Evaluation settings
eval_args: 
  split: {'RS':[0.6,0.2,0.2]}
  split_valid: {'RS':[0.6,0.2,0.2]}
  group_by: user
  order: RO
  mode: full
metrics: ['Recall', 'NDCG', 'Hit', 'MRR']
topk: [20]
valid_metric: Recall@20

# BiTGCF specific parameters (These are example parameters, you should refer to the BiTGCF paper or RecBole-CDR documentation for the actual parameters and their meanings)
num_forward_layers: 2
num_backward_layers: 2
# Add any other BiTGCF specific parameters here based on the documentation

# Save model settings
saved: True  # Ensure that model will be saved after training
checkpoint_dir: /home/tasi2425107/MyProjectExport/saved  # New directory where model will be saved
